# Aviation Accidents Analysis

You are part of a consulting firm that is tasked to do an analysis of commercial and passenger jet airline safety. The client (an airline/airplane insurer) is interested in knowing what types of aircraft (makes/models) exhibit low rates of total destruction and low likelihood of fatal or serious passenger injuries in the event of an accident. They are also interested in any general variables/conditions that might be at play. Your analysis will be based off of aviation accident data accumulated from the years 1948-2023. 

Our client is only interested in airplane makes/models that are professional builds and could potentially still be active. Assume a max lifetime of 40 years for a make/model retirement and make sure to filter your data accordingly (i.e. from 1983 onwards). They would also like separate recommendations for small aircraft vs. larger passenger models. **In addition, make sure that claims that you make are statistically robust and that you have enough samples when making comparisons between groups.**


In this summative assessment you will demonstrate your ability to:
- **Use Pandas to load, inspect, and clean the dataset appropriately.**
- **Transform relevant columns to create measures that address the problem at hand.**
- conduct EDA: visualization and statistical measures to systematically understand the structure of the data
- recommend a set of airplanes and makes conforming to the client's request and identify at least *two* factors contributing to airplane safety. You must provide supporting evidence (visuals, summary statistics, tables) for each claim you make.

### Make relevant library imports

In [68]:
#make all the required imports 
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings('ignore') # surpressing errors


# Set display options for better readability
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 100)

## Data Loading and Inspection

### Load in data from the relevant directory and inspect the dataframe.
- inspect NaNs, datatypes, and summary statistics

In [69]:
#load the csv and inspect it for null values ,and data types 
df = pd.read_csv("AviationData.csv", index_col=0, encoding='latin1')
df.shape

(88889, 30)

In [70]:
#check the top 5 rows 
df.head(5)

,Investigation.Type,Accident.Number,Event.Date,Location,Country,Latitude,Longitude,Airport.Code,Airport.Name,Injury.Severity,Aircraft.damage,Aircraft.Category,Registration.Number,Make,Model,Amateur.Built,Number.of.Engines,Engine.Type,FAR.Description,Schedule,Purpose.of.flight,Air.carrier,Total.Fatal.Injuries,Total.Serious.Injuries,Total.Minor.Injuries,Total.Uninjured,Weather.Condition,Broad.phase.of.flight,Report.Status,Publication.Date
Event.Id,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
20001218X45444,Accident,SEA87LA080,1948-10-24,"MOOSE CREEK, ID",United States,NaN,NaN,NaN,NaN,Fatal(2),Destroyed,NaN,NC6404,Stinson,108-3,No,1.0,Reciprocating,NaN,NaN,Personal,NaN,2.0,0.0,0.0,0.0,UNK,Cruise,Probable Cause,NaN
20001218X45447,Accident,LAX94LA336,1962-07-19,"BRIDGEPORT, CA",United States,NaN,NaN,NaN,NaN,Fatal(4),Destroyed,NaN,N5069P,Piper,PA24-180,No,1.0,Reciprocating,NaN,NaN,Personal,NaN,4.0,0.0,0.0,0.0,UNK,Unknown,Probable Cause,19-09-1996
20061025X01555,Accident,NYC07LA005,1974-08-30,"Saltville, VA",United States,36.922223,-81.878056,NaN,NaN,Fatal(3),Destroyed,NaN,N5142R,Cessna,172M,No,1.0,Reciprocating,NaN,NaN,Personal,NaN,3.0,NaN,NaN,NaN,IMC,Cruise,Probable Cause,26-02-2007
20001218X45448,Accident,LAX96LA321,1977-06-19,"EUREKA, CA",United States,NaN,NaN,NaN,NaN,Fatal(2),Destroyed,NaN,N1168J,Rockwell,112,No,1.0,Reciprocating,NaN,NaN,Personal,NaN,2.0,0.0,0.0,0.0,IMC,Cruise,Probable Cause,12-09-2000
20041105X01764,Accident,CHI79FA064,1979-08-02,"Canton, OH",United States,NaN,NaN,NaN,NaN,Fatal(1),Destroyed,NaN,N15NY,Cessna,501,No,NaN,NaN,NaN,NaN,Personal,NaN,1.0,2.0,NaN,0.0,VMC,Approach,Probable Cause,16-04-1980

In [71]:
#check the columns 
df.columns
df

,Investigation.Type,Accident.Number,Event.Date,Location,Country,Latitude,Longitude,Airport.Code,Airport.Name,Injury.Severity,Aircraft.damage,Aircraft.Category,Registration.Number,Make,Model,Amateur.Built,Number.of.Engines,Engine.Type,FAR.Description,Schedule,Purpose.of.flight,Air.carrier,Total.Fatal.Injuries,Total.Serious.Injuries,Total.Minor.Injuries,Total.Uninjured,Weather.Condition,Broad.phase.of.flight,Report.Status,Publication.Date
Event.Id,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
20001218X45444,Accident,SEA87LA080,1948-10-24,"MOOSE CREEK, ID",United States,NaN,NaN,NaN,NaN,Fatal(2),Destroyed,NaN,NC6404,Stinson,108-3,No,1.0,Reciprocating,NaN,NaN,Personal,NaN,2.0,0.0,0.0,0.0,UNK,Cruise,Probable Cause,NaN
20001218X45447,Accident,LAX94LA336,1962-07-19,"BRIDGEPORT, CA",United States,NaN,NaN,NaN,NaN,Fatal(4),Destroyed,NaN,N5069P,Piper,PA24-180,No,1.0,Reciprocating,NaN,NaN,Personal,NaN,4.0,0.0,0.0,0.0,UNK,Unknown,Probable Cause,19-09-1996
20061025X01555,Accident,NYC07LA005,1974-08-30,"Saltville, VA",United States,36.922223,-81.878056,NaN,NaN,Fatal(3),Destroyed,NaN,N5142R,Cessna,172M,No,1.0,Reciprocating,NaN,NaN,Personal,NaN,3.0,NaN,NaN,NaN,IMC,Cruise,Probable Cause,26-02-2007
20001218X45448,Accident,LAX96LA321,1977-06-19,"EUREKA, CA",United States,NaN,NaN,NaN,NaN,Fatal(2),Destroyed,NaN,N1168J,Rockwell,112,No,1.0,Reciprocating,NaN,NaN,Personal,NaN,2.0,0.0,0.0,0.0,IMC,Cruise,Probable Cause,12-09-2000
20041105X01764,Accident,CHI79FA064,1979-08-02,"Canton, OH",United States,NaN,NaN,NaN,NaN,Fatal(1),Destroyed,NaN,N15NY,Cessna,501,No,NaN,NaN,NaN,NaN,Personal,NaN,1.0,2.0,NaN,0.0,VMC,Approach,Probable Cause,16-04-1980
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20221227106491,Accident,ERA23LA093,2022-12-26,"Annapolis, MD",United States,NaN,NaN,NaN,NaN,Minor,NaN,NaN,N1867H,PIPER,PA-28-151,No,NaN,NaN,091,NaN,Personal,NaN,0.0,1.0,0.0,0.0,NaN,NaN,NaN,29-12-2022
20221227106494,Accident,ERA23LA095,2022-12-26,"Hampton, NH",United States,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N2895Z,BELLANCA,7ECA,No,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN
20221227106497,Accident,WPR23LA075,2022-12-26,"Payson, AZ",United States,341525N,1112021W,PAN,PAYSON,Non-Fatal,Substantial,Airplane,N749PJ,AMERICAN CHAMPION AIRCRAFT,8GCBC,No,1.0,NaN,091,NaN,Personal,NaN,0.0,0.0,0.0,1.0,VMC,NaN,NaN,27-12-2022
20221227106498,Accident,WPR23LA076,2022-12-26,"Morgan, UT",United States,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N210CU,CESSNA,210N,No,NaN,NaN,091,NaN,Personal,MC CESSNA 210N LLC,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN
20221230106513,Accident,ERA23LA097,2022-12-29,"Athens, GA",United States,NaN,NaN,NaN,NaN,Minor,NaN,NaN,N9026P,PIPER,PA-24-260,No,NaN,NaN,091,NaN,Personal,NaN,0.0,1.0,0.0,1.0,NaN,NaN,NaN,30-12-2022

In [72]:
#check data types 
df.info()

<class 'pandas.DataFrame'>
Index: 88889 entries, 20001218X45444 to 20221230106513
Data columns (total 30 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Investigation.Type      88889 non-null  str
 1   Accident.Number         88889 non-null  str
 2   Event.Date              88889 non-null  str
 3   Location                88837 non-null  str
 4   Country                 88663 non-null  str
 5   Latitude                34382 non-null  object
 6   Longitude               34373 non-null  object
 7   Airport.Code            50132 non-null  str
 8   Airport.Name            52704 non-null  str
 9   Injury.Severity         87889 non-null  str
 10  Aircraft.damage         85695 non-null  str
 11  Aircraft.Category       32287 non-null  str
 12  Registration.Number     87507 non-null  str
 13  Make                    88826 non-null  str
 14  Model                   88797 non-null  str
 15  Amateur.Built           88787 non-null  str
 16  Number.of.Engines       82805 non-null  float64
 17  Engine.Type             81793 non-null  str
 18  FAR.Description         32023 non-null  str
 19  Schedule                12582 non-null  str
 20  Purpose.of.flight       82697 non-null  str
 21  Air.carrier             16648 non-null  str
 22  Total.Fatal.Injuries    77488 non-null  float64
 23  Total.Serious.Injuries  76379 non-null  float64
 24  Total.Minor.Injuries    76956 non-null  float64
 25  Total.Uninjured         82977 non-null  float64
 26  Weather.Condition       84397 non-null  str
 27  Broad.phase.of.flight   61724 non-null  str
 28  Report.Status           82505 non-null  str
 29  Publication.Date        75118 non-null  str
dtypes: float64(5), object(2), str(23)
memory usage: 21.0+ MB

In [73]:
# Check for missing values (percentage)
missing_percentages = (df.isnull().sum() / len(df) * 100).sort_values(ascending=False)

print(missing_percentages[missing_percentages > 0])

Schedule                  85.845268
Air.carrier               81.271023
FAR.Description           63.974170
Aircraft.Category         63.677170
Longitude                 61.330423
Latitude                  61.320298
Airport.Code              43.601570
Airport.Name              40.708074
Broad.phase.of.flight     30.560587
Publication.Date          15.492356
Total.Serious.Injuries    14.073732
Total.Minor.Injuries      13.424608
Total.Fatal.Injuries      12.826109
Engine.Type                7.982990
Report.Status              7.181991
Purpose.of.flight          6.965991
Number.of.Engines          6.844491
Total.Uninjured            6.650992
Weather.Condition          5.053494
Aircraft.damage            3.593246
Registration.Number        1.554748
Injury.Severity            1.124999
Country                    0.254250
Amateur.Built              0.114750
Model                      0.103500
Make                       0.070875
Location                   0.058500
dtype: float64

In [74]:
#preliminary analysis
df.describe().T

,count,mean,std,min,25%,50%,75%,max
Number.of.Engines,82805.0,1.146585,0.446510,0.0,1.0,1.0,1.0,8.0
Total.Fatal.Injuries,77488.0,0.647855,5.485960,0.0,0.0,0.0,0.0,349.0
Total.Serious.Injuries,76379.0,0.279881,1.544084,0.0,0.0,0.0,0.0,161.0
Total.Minor.Injuries,76956.0,0.357061,2.235625,0.0,0.0,0.0,0.0,380.0
Total.Uninjured,82977.0,5.325440,27.913634,0.0,0.0,1.0,2.0,699.0

In [75]:
df.describe(include='number').T

,count,mean,std,min,25%,50%,75%,max
Number.of.Engines,82805.0,1.146585,0.446510,0.0,1.0,1.0,1.0,8.0
Total.Fatal.Injuries,77488.0,0.647855,5.485960,0.0,0.0,0.0,0.0,349.0
Total.Serious.Injuries,76379.0,0.279881,1.544084,0.0,0.0,0.0,0.0,161.0
Total.Minor.Injuries,76956.0,0.357061,2.235625,0.0,0.0,0.0,0.0,380.0
Total.Uninjured,82977.0,5.325440,27.913634,0.0,0.0,1.0,2.0,699.0

In [76]:
#describe categoricals calumns 
df.describe(include='O').T

                       count unique             top   freq
Investigation.Type     88889      2        Accident  85015
Accident.Number        88889  88863      ERA22LA103      2
Event.Date             88889  14782      1982-05-16     25
Location               88837  27758   ANCHORAGE, AK    434
Country                88663    219   United States  82248
Latitude               34382  25592         332739N     19
Longitude              34373  27156        0112457W     24
Airport.Code           50132  10374            NONE   1488
Airport.Name           52704  24870         Private    240
Injury.Severity        87889    109       Non-Fatal  67357
Aircraft.damage        85695      4     Substantial  64148
Aircraft.Category      32287     15        Airplane  27617
Registration.Number    87507  79104            NONE    344
Make                   88826   8237          Cessna  22227
Model                  88797  12318             152   2367
Amateur.Built          88787      2              No  80312
Engine.Type            81793     12   Reciprocating  69530
FAR.Description        32023     31             091  18221
Schedule               12582      3            NSCH   4474
Purpose.of.flight      82697     26        Personal  49448
Air.carrier            16648  13590           Pilot    258
Weather.Condition      84397      4             VMC  77303
Broad.phase.of.flight  61724     12         Landing  15428
Report.Status          82505  17074  Probable Cause  61754
Publication.Date       75118   2924      25-09-2020  17019

## Data Cleaning

### Filtering aircrafts and events

We want to filter the dataset to include aircraft that the client is interested in an analysis of:
- inspect relevant columns
- figure out any reasonable imputations
- filter the dataset

In [77]:
#make a copy 
airline_df=df.copy(deep=True)
airline_df

,Investigation.Type,Accident.Number,Event.Date,Location,Country,Latitude,Longitude,Airport.Code,Airport.Name,Injury.Severity,Aircraft.damage,Aircraft.Category,Registration.Number,Make,Model,Amateur.Built,Number.of.Engines,Engine.Type,FAR.Description,Schedule,Purpose.of.flight,Air.carrier,Total.Fatal.Injuries,Total.Serious.Injuries,Total.Minor.Injuries,Total.Uninjured,Weather.Condition,Broad.phase.of.flight,Report.Status,Publication.Date
Event.Id,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
20001218X45444,Accident,SEA87LA080,1948-10-24,"MOOSE CREEK, ID",United States,NaN,NaN,NaN,NaN,Fatal(2),Destroyed,NaN,NC6404,Stinson,108-3,No,1.0,Reciprocating,NaN,NaN,Personal,NaN,2.0,0.0,0.0,0.0,UNK,Cruise,Probable Cause,NaN
20001218X45447,Accident,LAX94LA336,1962-07-19,"BRIDGEPORT, CA",United States,NaN,NaN,NaN,NaN,Fatal(4),Destroyed,NaN,N5069P,Piper,PA24-180,No,1.0,Reciprocating,NaN,NaN,Personal,NaN,4.0,0.0,0.0,0.0,UNK,Unknown,Probable Cause,19-09-1996
20061025X01555,Accident,NYC07LA005,1974-08-30,"Saltville, VA",United States,36.922223,-81.878056,NaN,NaN,Fatal(3),Destroyed,NaN,N5142R,Cessna,172M,No,1.0,Reciprocating,NaN,NaN,Personal,NaN,3.0,NaN,NaN,NaN,IMC,Cruise,Probable Cause,26-02-2007
20001218X45448,Accident,LAX96LA321,1977-06-19,"EUREKA, CA",United States,NaN,NaN,NaN,NaN,Fatal(2),Destroyed,NaN,N1168J,Rockwell,112,No,1.0,Reciprocating,NaN,NaN,Personal,NaN,2.0,0.0,0.0,0.0,IMC,Cruise,Probable Cause,12-09-2000
20041105X01764,Accident,CHI79FA064,1979-08-02,"Canton, OH",United States,NaN,NaN,NaN,NaN,Fatal(1),Destroyed,NaN,N15NY,Cessna,501,No,NaN,NaN,NaN,NaN,Personal,NaN,1.0,2.0,NaN,0.0,VMC,Approach,Probable Cause,16-04-1980
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20221227106491,Accident,ERA23LA093,2022-12-26,"Annapolis, MD",United States,NaN,NaN,NaN,NaN,Minor,NaN,NaN,N1867H,PIPER,PA-28-151,No,NaN,NaN,091,NaN,Personal,NaN,0.0,1.0,0.0,0.0,NaN,NaN,NaN,29-12-2022
20221227106494,Accident,ERA23LA095,2022-12-26,"Hampton, NH",United States,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N2895Z,BELLANCA,7ECA,No,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN
20221227106497,Accident,WPR23LA075,2022-12-26,"Payson, AZ",United States,341525N,1112021W,PAN,PAYSON,Non-Fatal,Substantial,Airplane,N749PJ,AMERICAN CHAMPION AIRCRAFT,8GCBC,No,1.0,NaN,091,NaN,Personal,NaN,0.0,0.0,0.0,1.0,VMC,NaN,NaN,27-12-2022
20221227106498,Accident,WPR23LA076,2022-12-26,"Morgan, UT",United States,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N210CU,CESSNA,210N,No,NaN,NaN,091,NaN,Personal,MC CESSNA 210N LLC,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN
20221230106513,Accident,ERA23LA097,2022-12-29,"Athens, GA",United States,NaN,NaN,NaN,NaN,Minor,NaN,NaN,N9026P,PIPER,PA-24-260,No,NaN,NaN,091,NaN,Personal,NaN,0.0,1.0,0.0,1.0,NaN,NaN,NaN,30-12-2022

In [78]:
#remove whitesspace remove the dots in between words and make it all small letters 
#change regex to false so (.)is treated as a charracyers 
airline_df.columns = df.columns.str.replace(".", "_", regex=False).str.lower().str.strip()
airline_df

,investigation_type,accident_number,event_date,location,country,latitude,longitude,airport_code,airport_name,injury_severity,aircraft_damage,aircraft_category,registration_number,make,model,amateur_built,number_of_engines,engine_type,far_description,schedule,purpose_of_flight,air_carrier,total_fatal_injuries,total_serious_injuries,total_minor_injuries,total_uninjured,weather_condition,broad_phase_of_flight,report_status,publication_date
Event.Id,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
20001218X45444,Accident,SEA87LA080,1948-10-24,"MOOSE CREEK, ID",United States,NaN,NaN,NaN,NaN,Fatal(2),Destroyed,NaN,NC6404,Stinson,108-3,No,1.0,Reciprocating,NaN,NaN,Personal,NaN,2.0,0.0,0.0,0.0,UNK,Cruise,Probable Cause,NaN
20001218X45447,Accident,LAX94LA336,1962-07-19,"BRIDGEPORT, CA",United States,NaN,NaN,NaN,NaN,Fatal(4),Destroyed,NaN,N5069P,Piper,PA24-180,No,1.0,Reciprocating,NaN,NaN,Personal,NaN,4.0,0.0,0.0,0.0,UNK,Unknown,Probable Cause,19-09-1996
20061025X01555,Accident,NYC07LA005,1974-08-30,"Saltville, VA",United States,36.922223,-81.878056,NaN,NaN,Fatal(3),Destroyed,NaN,N5142R,Cessna,172M,No,1.0,Reciprocating,NaN,NaN,Personal,NaN,3.0,NaN,NaN,NaN,IMC,Cruise,Probable Cause,26-02-2007
20001218X45448,Accident,LAX96LA321,1977-06-19,"EUREKA, CA",United States,NaN,NaN,NaN,NaN,Fatal(2),Destroyed,NaN,N1168J,Rockwell,112,No,1.0,Reciprocating,NaN,NaN,Personal,NaN,2.0,0.0,0.0,0.0,IMC,Cruise,Probable Cause,12-09-2000
20041105X01764,Accident,CHI79FA064,1979-08-02,"Canton, OH",United States,NaN,NaN,NaN,NaN,Fatal(1),Destroyed,NaN,N15NY,Cessna,501,No,NaN,NaN,NaN,NaN,Personal,NaN,1.0,2.0,NaN,0.0,VMC,Approach,Probable Cause,16-04-1980
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20221227106491,Accident,ERA23LA093,2022-12-26,"Annapolis, MD",United States,NaN,NaN,NaN,NaN,Minor,NaN,NaN,N1867H,PIPER,PA-28-151,No,NaN,NaN,091,NaN,Personal,NaN,0.0,1.0,0.0,0.0,NaN,NaN,NaN,29-12-2022
20221227106494,Accident,ERA23LA095,2022-12-26,"Hampton, NH",United States,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N2895Z,BELLANCA,7ECA,No,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN
20221227106497,Accident,WPR23LA075,2022-12-26,"Payson, AZ",United States,341525N,1112021W,PAN,PAYSON,Non-Fatal,Substantial,Airplane,N749PJ,AMERICAN CHAMPION AIRCRAFT,8GCBC,No,1.0,NaN,091,NaN,Personal,NaN,0.0,0.0,0.0,1.0,VMC,NaN,NaN,27-12-2022
20221227106498,Accident,WPR23LA076,2022-12-26,"Morgan, UT",United States,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N210CU,CESSNA,210N,No,NaN,NaN,091,NaN,Personal,MC CESSNA 210N LLC,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN
20221230106513,Accident,ERA23LA097,2022-12-29,"Athens, GA",United States,NaN,NaN,NaN,NaN,Minor,NaN,NaN,N9026P,PIPER,PA-24-260,No,NaN,NaN,091,NaN,Personal,NaN,0.0,1.0,0.0,1.0,NaN,NaN,NaN,30-12-2022

In [79]:
# First, let's convert Event_Date to datetime
airline_df['event_date'] = pd.to_datetime(airline_df['event_date'], errors='coerce')

# Extract year for filtering
airline_df['Year'] = airline_df['event_date'].dt.year


print(f"From: {airline_df['Year'].min()} to {airline_df['Year'].max()}")
print(f"\nTotal records: {len(airline_df)}")

From: 1948 to 2022

Total records: 88889

In [80]:
# Filter for accidents from 1983 onwards (40-year max lifetime)
airline_df = airline_df[airline_df['Year'] >= 1983].copy()
print(f"Records after filtering for 1983+: {len(airline_df)}")

Records after filtering for 1983+: 85289

In [81]:
#inspect the aircraft_category and filter out for airplane only

airline_df=airline_df[airline_df["aircraft_category"]=='Airplane'].copy()
print(f"Records after filtering for Airplanes only: {len(airline_df)}")

Records after filtering for Airplanes only: 24441

In [82]:
#confirmed type after all the changes 
type(airline_df)

pandas.DataFrame

### Cleaning and constructing Key Measurables

Injuries and robustness to destruction are a key interest point for the client. Clean and impute relevant columns and then create derived fields that best quantifies what the client wishes to track. **Use commenting or markdown to explain any cleaning assumptions as well as any derived columns you create.**

**Construct metric for fatal/serious injuries**

*Hint:* Estimate the total number of passengers on each flight. The likelihood of serious / fatal injury can be estimated as a fraction from this.

In [83]:
# Inspect injury-related columns
injury_cols = ['total_fatal_injuries', 'total_serious_injuries', 
               'total_minor_injuries', 'total_uninjured']

# Show missing data percentages
print("Missing Values (%):")
missing_pct = (airline_df[injury_cols].isnull().sum() / len(airline_df) * 100)
print(missing_pct)

print("\nBasic Statistics:")
print(airline_df[injury_cols].describe())

Missing Values (%):
total_fatal_injuries      12.884088
total_serious_injuries    13.113211
total_minor_injuries      11.697557
total_uninjured            3.649605
dtype: float64

Basic Statistics:
       total_fatal_injuries  total_serious_injuries  total_minor_injuries  \
count          21292.000000            21236.000000          21582.000000
mean               0.694768                0.314278              0.250857
std                6.354876                2.235199              3.067366
min                0.000000                0.000000              0.000000
25%                0.000000                0.000000              0.000000
50%                0.000000                0.000000              0.000000
75%                0.000000                0.000000              0.000000
max              295.000000              161.000000            380.000000

       total_uninjured
count     23549.000000
mean          6.897151
std          33.562436
min           0.000000
25%           0.000000
50%           1.000000
75%           2.000000
max         588.000000

In [84]:
# Fill missing injury values with 0 (assumption: if not reported, assume 0)
# This is reasonable as fatal/serious injuries would likely be reported
airline_df['total_fatal_injuries'] = airline_df['total_fatal_injuries'].fillna(0)
airline_df['total_serious_injuries'] = airline_df['total_serious_injuries'].fillna(0)
airline_df['total_minor_injuries'] = airline_df['total_minor_injuries'].fillna(0)
airline_df['total_uninjured'] = airline_df['total_uninjured'].fillna(0)

# Calculate total passengers (sum of all injury categories)
airline_df['total_passengers'] = (airline_df['total_fatal_injuries'] + 
                                   airline_df['total_serious_injuries'] + 
                                   airline_df['total_minor_injuries'] + 
                                   airline_df['total_uninjured'])

# Calculate serious/fatal injuries combined
airline_df['fatal_serious_injuries'] = airline_df['total_fatal_injuries'] + airline_df['total_serious_injuries']

# Calculate fraction of passengers with fatal/serious injuries
# Returns NaN automatically where total_passengers = 0 (division by zero)
airline_df['fatal_serious_fraction'] = (
    airline_df['fatal_serious_injuries'] / airline_df['total_passengers']
)

"""New injury metrics created:
  total_passengers: sum of all injury categories
  fatal_serious_injuries: fatal + serious injuries combined
  fatal_serious_fraction: fraction of passengers with fatal/serious injuries"""


print(f"\nSample statistics for fatal_serious_fraction:")
print(airline_df['fatal_serious_fraction'].describe())

Sample statistics for fatal_serious_fraction:
count    23521.000000
mean         0.295827
std          0.437939
min          0.000000
25%          0.000000
50%          0.000000
75%          1.000000
max          1.000000
Name: fatal_serious_fraction, dtype: float64

New injury metrics created:
  total_passengers: sum of all injury categories
  fatal_serious_injuries: fatal + serious injuries combined
  fatal_serious_fraction: fraction of passengers with fatal/serious injuries

**Aircraft.Damage**
- identify and execute any cleaning tasks
- construct a derived column tracking whether an aircraft was destroyed or not.

In [85]:
# Inspect Aircraft_damage column
print(airline_df['aircraft_damage'].value_counts(dropna=False))

aircraft_damage
Substantial    19612
Destroyed       2637
NaN             1238
Minor            854
Unknown          100
Name: count, dtype: int64

cleaning was done to remove whitspace and (.)so we can proceed

### Investigate the *Make* column
- Identify cleaning tasks here
- List cleaning tasks clearly in markdown
- Execute the cleaning tasks
- For your analysis, keep Makes with a reasonable number (you can put the threshold at 50 though lower could work as well)

In [86]:
# Inspect Make column
print(f"Total unique makes: {airline_df['make'].nunique()}")
print(f"Missing values: {airline_df['make'].isnull().sum()}")
print("\nTop 20 makes by frequency:")
print(airline_df['make'].value_counts().head(20))

Total unique makes: 3742
Missing values: 4

Top 20 makes by frequency:
make
CESSNA                4867
PIPER                 2805
Cessna                2283
Piper                 1189
BOEING                1037
BEECH                 1018
Beech                  416
Boeing                 242
MOONEY                 238
CIRRUS DESIGN CORP     218
AIR TRACTOR INC        217
AIRBUS                 216
BELLANCA               158
AERONCA                149
MAULE                  144
Mooney                 125
EMBRAER                123
Air Tractor            117
LUSCOMBE                95
STINSON                 91
Name: count, dtype: int64

**Make Column Cleaning Tasks Identified:**
1. Drop rows with missing Make values

2. Consolidate manufacturer name variations (e.g. "Beech" vs "Beechcraft")

In [88]:
# 1. Drop missing Make values
airline_df = airline_df.dropna(subset=['make'])

# Standardize to title case first (handles ALL CAPS problem)
airline_df['make'] = airline_df['make'].str.strip().str.title()


# 2. Consolidate known manufacturer name variations
make_replacements = {
    'Beech': 'Beechcraft',
    'Mcdonnell Douglas': 'McDonnell Douglas',
    'Mcdonnell Douglas Aircraft Co': 'McDonnell Douglas',
    'Boeing Co': 'Boeing',
    'Piper Aircraft': 'Piper',
    'Grumman American': 'Grumman',
    'Cirrus Design Corp': 'Cirrus',
    'Air Tractor Inc': 'Air Tractor',
    'Bombardier Inc': 'Bombardier',  # add this
    'Aviat Aircraft Inc': 'Aviat'
}
airline_df['make'] = airline_df['make'].replace(make_replacements)

# 5. Keep only makes with 50+ accidents for statistical robustness
make_counts = airline_df['make'].value_counts()
valid_makes = make_counts[make_counts >= 50].index
airline_df = airline_df[airline_df['make'].isin(valid_makes)]

print(f"Remaining records: {len(airline_df)}")
print(f"Remaining unique makes: {airline_df['make'].nunique()}")
print("\nMakes kept:")
print(airline_df['make'].value_counts())

Remaining records: 18156
Remaining unique makes: 34

Makes kept:
make
Cessna                            7150
Piper                             4001
Beechcraft                        1448
Boeing                            1279
Air Tractor                        425
Mooney                             363
Cirrus                             357
Airbus                             245
Bellanca                           220
Maule                              215
Aeronca                            200
Grumman                            173
Champion                           158
Embraer                            153
Aviat                              146
Luscombe                           141
Stinson                            129
Vans                               125
McDonnell Douglas                  116
Bombardier                         115
North American                     106
Dehavilland                         95
Taylorcraft                         93
Aero Commander                      90
Socata                              75
Diamond Aircraft Ind Inc            74
De Havilland                        73
Raytheon Aircraft Company           62
Rockwell International              58
Grumman Acft Eng Cor-Schweizer      58
Ayres                               55
Rans                                54
Ercoupe                             52
American Champion Aircraft          52
Name: count, dtype: int64

### Inspect Model column
- Get rid of any NaNs.
- Inspect the column and counts for each model/make. Are model labels unique to each make?
- If not, create a derived column that is a unique identifier for a given plane type.

In [89]:
airline_df.columns

Index(['investigation_type', 'accident_number', 'event_date', 'location',
       'country', 'latitude', 'longitude', 'airport_code', 'airport_name',
       'injury_severity', 'aircraft_damage', 'aircraft_category',
       'registration_number', 'make', 'model', 'amateur_built',
       'number_of_engines', 'engine_type', 'far_description', 'schedule',
       'purpose_of_flight', 'air_carrier', 'total_fatal_injuries',
       'total_serious_injuries', 'total_minor_injuries', 'total_uninjured',
       'weather_condition', 'broad_phase_of_flight', 'report_status',
       'publication_date', 'Year', 'total_passengers',
       'fatal_serious_injuries', 'fatal_serious_fraction'],
      dtype='str')

In [90]:
# Inspect Model column
print(f"Missing Model values: {airline_df['model'].isnull().sum()}")
print(f"Total unique models: {airline_df['model'].nunique()}")
 
#remove empty rows in models
airline_df=airline_df.dropna(subset='model')
print(f"Missing values after dropping: {airline_df['make'].isnull().sum()}")

Missing Model values: 13
Total unique models: 2118
Missing values after dropping: 0

In [91]:
# Check if model names are unique across makes
print(airline_df.groupby('model')['make'].nunique().sort_values(ascending=False).head(10))

model
8KCAB    3
500      3
7AC      3
7GCBC    3
8GCBC    3
400      3
7GCAA    3
7EC      3
7ECA     3
S2R      3
Name: make, dtype: int64

In [92]:
# Since models are not unique across makes, create a unique identifier
# Combine Make and Model to create a unique aircraft type identifier
airline_df['make_model']=airline_df['make']+' '+airline_df['model']
print(airline_df['make_model'].value_counts().head(15))

make_model
Cessna 172         769
Boeing 737         404
Cessna 152         316
Cessna 182         304
Cessna 172S        276
Piper PA28         273
Cessna 172N        249
Cirrus SR22        240
Cessna 180         213
Cessna 172M        180
Cessna 150         179
Piper PA-18-150    175
Piper PA-28-140    169
Beechcraft A36     165
Cessna 172P        143
Name: count, dtype: int64

### Cleaning other columns
- there are other columns containing data that might be related to the outcome of an accident. We list a few here:
- Engine.Type
- Weather.Condition
- Number.of.Engines
- Purpose.of.flight
- Broad.phase.of.flight

Inspect and identify potential cleaning tasks in each of the above columns. Execute those cleaning tasks. 

**Note**: You do not necessarily need to impute or drop NaNs here.

In [93]:
# Inspect all columns at once
cols = ['engine_type', 'weather_condition', 'number_of_engines', 
        'purpose_of_flight', 'broad_phase_of_flight']

for col in cols:
    print(airline_df[col].value_counts(dropna=False))

engine_type
Reciprocating      13001
NaN                 3285
Turbo Prop           933
Turbo Fan            711
Unknown              119
Turbo Jet             72
Geared Turbofan       12
Turbo Shaft            9
UNK                    1
Name: count, dtype: int64
weather_condition
VMC    14499
NaN     2457
IMC      913
Unk      188
UNK       86
Name: count, dtype: int64
number_of_engines
1.0    13408
2.0     2484
NaN     2153
4.0       67
3.0       26
0.0        5
Name: count, dtype: int64
purpose_of_flight
Personal                     10028
NaN                           3094
Instructional                 2419
Aerial Application             726
Business                       411
Unknown                        317
Positioning                    269
Skydiving                      157
Aerial Observation             148
Other Work Use                 121
Banner Tow                      86
Flight Test                     75
Ferry                           72
Executive/corporate             66
Glider Tow                      29
Public Aircraft - Federal       28
Public Aircraft                 27
Public Aircraft - State         21
Air Race show                   17
Firefighting                    12
Public Aircraft - Local         11
PUBS                             3
Air Race/show                    2
Air Drop                         2
ASHO                             2
Name: count, dtype: int64
broad_phase_of_flight
NaN            15669
Landing         1119
Takeoff          431
Cruise           240
Approach         213
Maneuvering      128
Taxi              99
Go-around         81
Descent           63
Climb             52
Standing          35
Unknown           11
Other              2
Name: count, dtype: int64

###now down to the cleaning required

1. Fix weather_condition - consolidate Unk/UNK into one
2. Fix engine_type - consolidate Unknown/UNK into one
3. Fix number_of_engines - 0 engines is impossible, replace with NaN
4. Fix broad_phase_of_flight - standardize Unknown

In [ ]:
# Fix weather_condition - consolidate Unk/UNK into one
airline_df['weather_condition'] = airline_df['weather_condition'].replace({'Unk': 'UNK', 'Unk': 'UNK'})

# Fix engine_type - consolidate Unknown/UNK into one
airline_df['engine_type'] = airline_df['engine_type'].replace({'Unk': 'Unknown'})

# Fix number_of_engines - 0 engines is impossible, replace with NaN
airline_df['number_of_engines'] = airline_df['number_of_engines'].replace(0.0, np.nan)

# Fix broad_phase_of_flight - standardize Unknown
airline_df['broad_phase_of_flight'] = airline_df['broad_phase_of_flight'].replace({'UNKNOWN': 'Unknown'})


for col in cols:
    print(f"\n{col}:")
    print(airline_df[col].value_counts(dropna=False))

engine_type:
engine_type
Reciprocating      13001
NaN                 3285
Turbo Prop           933
Turbo Fan            711
Unknown              119
Turbo Jet             72
Geared Turbofan       12
Turbo Shaft            9
UNK                    1
Name: count, dtype: int64

weather_condition:
weather_condition
VMC    14499
NaN     2457
IMC      913
UNK      274
Name: count, dtype: int64

number_of_engines:
number_of_engines
1.0    13408
2.0     2484
NaN     2158
4.0       67
3.0       26
Name: count, dtype: int64

purpose_of_flight:
purpose_of_flight
Personal                     10028
NaN                           3094
Instructional                 2419
Aerial Application             726
Business                       411
Unknown                        317
Positioning                    269
Skydiving                      157
Aerial Observation             148
Other Work Use                 121
Banner Tow                      86
Flight Test                     75
Ferry                           72
Executive/corporate             66
Glider Tow                      29
Public Aircraft - Federal       28
Public Aircraft                 27
Public Aircraft - State         21
Air Race show                   17
Firefighting                    12
Public Aircraft - Local         11
PUBS                             3
Air Race/show                    2
Air Drop                         2
ASHO                             2
Name: count, dtype: int64

broad_phase_of_flight:
broad_phase_of_flight
NaN            15669
Landing         1119
Takeoff          431
Cruise           240
Approach         213
Maneuvering      128
Taxi              99
Go-around         81
Descent           63
Climb             52
Standing          35
Unknown           11
Other              2
Name: count, dtype: int64

### Column Removal
- inspect the dataframe and drop any columns that have too many NaNs

In [95]:
# Check missing value percentages for all columns
missing_pct = (airline_df.isnull().sum() / len(airline_df) * 100).sort_values(ascending=False)
print(missing_pct[missing_pct > 0])

schedule                  88.022929
broad_phase_of_flight     86.363887
air_carrier               53.083834
airport_code              34.883977
airport_name              34.283195
report_status             21.330541
engine_type               18.106157
purpose_of_flight         17.053409
weather_condition         13.542413
number_of_engines         11.894395
longitude                 10.692829
latitude                  10.676294
aircraft_damage            5.892080
publication_date           4.497602
fatal_serious_fraction     4.387367
injury_severity            3.979496
far_description            1.945654
registration_number        1.003142
amateur_built              0.071653
location                   0.027559
country                    0.005512
dtype: float64

In [96]:
# Drop columns with >70% missing values
missing_pct = airline_df.isnull().sum() / len(airline_df) * 100
cols_to_drop = missing_pct[missing_pct > 50].index.tolist()
airline_df = airline_df.drop(columns=cols_to_drop)

print(f"Dropped {len(cols_to_drop)} columns: {cols_to_drop}")
print(f"Remaining columns: {airline_df.shape[1]}")

Dropped 3 columns: ['schedule', 'air_carrier', 'broad_phase_of_flight']
Remaining columns: 32

In [97]:
# Check missing value percentages for all columns
missing_pct = (airline_df.isnull().sum() / len(airline_df) * 100).sort_values(ascending=False)
print(missing_pct[missing_pct > 0])

airport_code              34.883977
airport_name              34.283195
report_status             21.330541
engine_type               18.106157
purpose_of_flight         17.053409
weather_condition         13.542413
number_of_engines         11.894395
longitude                 10.692829
latitude                  10.676294
aircraft_damage            5.892080
publication_date           4.497602
fatal_serious_fraction     4.387367
injury_severity            3.979496
far_description            1.945654
registration_number        1.003142
amateur_built              0.071653
location                   0.027559
country                    0.005512
dtype: float64

In [98]:
#columns we wont need dropped
cols_to_drop = ['airport_code', 'airport_name', 
                'longitude', 'latitude', 'registration_number',
                'publication_date', 'report_status']

airline_df = airline_df.drop(columns=cols_to_drop)
print(f"Remaining columns: {airline_df.shape[1]}")

Remaining columns: 25

In [99]:
# Check missing value percentages for all columns
missing_pct = (airline_df.isnull().sum() / len(airline_df) * 100).sort_values(ascending=False)
print(missing_pct[missing_pct > 0])

engine_type               18.106157
purpose_of_flight         17.053409
weather_condition         13.542413
number_of_engines         11.894395
aircraft_damage            5.892080
fatal_serious_fraction     4.387367
injury_severity            3.979496
far_description            1.945654
amateur_built              0.071653
location                   0.027559
country                    0.005512
dtype: float64

### Save DataFrame to csv
- its generally useful to save data to file/server after its in a sufficiently cleaned or intermediate state
- the data can then be loaded directly in another notebook for further analysis
- this helps keep your notebooks and workflow readable, clean and modularized

In [100]:
# Save cleaned dataframe to CSV
airline_df.to_csv('AviationData_Cleaned.csv', index=False)
print(f"Saved! Shape: {airline_df.shape}")

Saved! Shape: (18143, 25)